added container tags' explanation and example
StarHPC/docs pull request #18
Opened 2024-12-20 19:56 UTC by manitofigh

2025-02-27 17:59 UTC, alex-rosenberg35 requested changes
Inserting the container tags section here breaks the flow of the existing content and places existing unrelated content into the new section. For example, the "Note the nvcr.io/nvidia/pytorch:23.05-py3 section of the command... In Pytorch's case, this command is going to take..." content references the command just provided in the "Pull and run Pytorch" section. After your change, that note would appear in the "Container Tags" section too, even though it is unrelated.

2025-03-25 21:59 UTC, alex-rosenberg35 requested changes
@manitofigh It looks like you moved the bulk of the content from the "Pull and run Pytorch" subsection of the NGC Pytorch example when you moved the "Container Tag" section. So now the NGC Pytorch example is incomplete and "Pulling from Docker Hub" starts with tensorflow but then goes abruptly to Pytorch. Please actually build and read the page when you make changes.

2025-04-15 20:32 UTC, MKhlystun approved these changes

2025-04-15 20:37 UTC, alex-rosenberg35 approved these changes

2025-04-15 20:37 UTC, merged